apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend3-deployment
  labels:
    cyouapp: backend3
spec:
  replicas: 2
  selector:
    matchLabels:
      cyouapp: backend3
  template:
    metadata:
      labels:
        cyouapp: backend3
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: true
      imagePullSecrets:
      - name: regcred
      containers:
      - name: backend3
        image: 99.0.0.5/for-test/backend:v1.8
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: backend3-service
spec:
  selector:
    cyouapp: backend3
  ports:
  - name: backend3
    protocol: TCP
    port: 50051
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend3-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: backend3-deployment
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 30
